### ISSUE TITLE
Add client-side routing scaffolding

### ISSUE THREAD

**Issue by MatthewCYLau** [deloitte-uk-systems-engineering/quickstart-react-material-ui#2]
Add page/layout scaffolding.

**Comment by rmcgeehan-deloitte** [comment]
This is a great idea - and one of my higher priorities for enhancing the quickstart app. I've seen many anti-patterns when it comes to routing in react apps so it would be great to set a standard with helpful comments + links.

**Comment by MatthewCYLau** [comment]
Done.
